version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    networks: 
      - proxy
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 8080:80/tcp
      # - 443:443/tcp
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    restart: unless-stopped
volumes:
  work:
  conf:
networks:
  proxy:
    external: true
