version: "3.8"
services:
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports: 
      - 80:80
    volumes:
      - data:/data
    networks:
      - proxy
    environment:
      TZ: 'Europe/Berlin'
volumes:
  data:
    driver: local
networks:
  proxy:
    external: true
