version: '3.8'
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    networks:
      - proxy
    volumes:
      - data:/app/data
    ports:
      - 3001:3001
volumes:
  data:
networks:
  proxy:
    external: true
